apiVersion: v1
kind: ServiceAccount
metadata:
  name: testsa
  namespace: testns

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-testns
  namespace: testns
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebind-testns
  namespace: testns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-testns
subjects:
  - kind: ServiceAccount
    name: testsa

